-- MySQL Script generated by MySQL Workbench
-- Sun Apr  3 18:30:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Civil Aviation Authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Civil Aviation Authority` (
  `id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport` (
  `international airport code` CHAR(3) NOT NULL,
  `code` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `Civil Aviation Authority_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`international airport code`),
  INDEX `fk_Airport_Civil Aviation Authority1_idx` (`Civil Aviation Authority_id` ASC) VISIBLE,
  CONSTRAINT `fk_Airport_Civil Aviation Authority1`
    FOREIGN KEY (`Civil Aviation Authority_id`)
    REFERENCES `mydb`.`Civil Aviation Authority` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Model` (
  `maker` VARCHAR(45) NOT NULL,
  `seats` INT UNSIGNED NOT NULL,
  `weight` DOUBLE NOT NULL,
  PRIMARY KEY (`maker`, `seats`, `weight`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aircraft` (
  `id` INT UNSIGNED NOT NULL,
  `Airport_international airport code` CHAR(3) NOT NULL,
  `Model_maker` VARCHAR(45) NOT NULL,
  `Model_seats` INT UNSIGNED NOT NULL,
  `Model_weight` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Aircraft_Airport_idx` (`Airport_international airport code` ASC) VISIBLE,
  INDEX `fk_Aircraft_Model1_idx` (`Model_maker` ASC, `Model_seats` ASC, `Model_weight` ASC) VISIBLE,
  CONSTRAINT `fk_Aircraft_Airport`
    FOREIGN KEY (`Airport_international airport code`)
    REFERENCES `mydb`.`Airport` (`international airport code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aircraft_Model1`
    FOREIGN KEY (`Model_maker` , `Model_seats` , `Model_weight`)
    REFERENCES `mydb`.`Model` (`maker` , `seats` , `weight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airline` (
  `airline international code` INT UNSIGNED NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `activity status` TINYINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`airline international code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight` (
  `flightt's code` INT UNSIGNED NOT NULL,
  `international code of departure airport` CHAR(3) NOT NULL,
  `international code of arrival airport` CHAR(3) NOT NULL,
  `Airline_airline international code` INT UNSIGNED NOT NULL,
  `arrival day` DATE NOT NULL,
  `arrival time` TIME NOT NULL,
  `departure day` DATE NOT NULL,
  `departure time` TIME NOT NULL,
  PRIMARY KEY (`flightt's code`),
  INDEX `fk_Flight_Airport1_idx` (`international code of departure airport` ASC) VISIBLE,
  INDEX `fk_Flight_Airport2_idx` (`international code of arrival airport` ASC) VISIBLE,
  INDEX `fk_Flight_Airline1_idx` (`Airline_airline international code` ASC) VISIBLE,
  CONSTRAINT `fk_Flight_Airport1`
    FOREIGN KEY (`international code of departure airport`)
    REFERENCES `mydb`.`Airport` (`international airport code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airport2`
    FOREIGN KEY (`international code of arrival airport`)
    REFERENCES `mydb`.`Airport` (`international airport code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airline1`
    FOREIGN KEY (`Airline_airline international code`)
    REFERENCES `mydb`.`Airline` (`airline international code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seat Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seat Type` (
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight_has_Seat Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight_has_Seat Type` (
  `Flight_flightt's code` INT UNSIGNED NOT NULL,
  `Seat Type_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Flight_flightt's code`, `Seat Type_type`),
  INDEX `fk_Flight_has_Seat Type_Seat Type1_idx` (`Seat Type_type` ASC) VISIBLE,
  INDEX `fk_Flight_has_Seat Type_Flight1_idx` (`Flight_flightt's code` ASC) VISIBLE,
  CONSTRAINT `fk_Flight_has_Seat Type_Flight1`
    FOREIGN KEY (`Flight_flightt's code`)
    REFERENCES `mydb`.`Flight` (`flightt's code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_has_Seat Type_Seat Type1`
    FOREIGN KEY (`Seat Type_type`)
    REFERENCES `mydb`.`Seat Type` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `options` TEXT(1000) NOT NULL,
  `Seat Type_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`options`),
  INDEX `fk_Menu_Seat Type1_idx` (`Seat Type_type` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_Seat Type1`
    FOREIGN KEY (`Seat Type_type`)
    REFERENCES `mydb`.`Seat Type` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passenger` (
  `passport id` VARCHAR(45) NOT NULL,
  `Flight_flightt's code` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`passport id`),
  INDEX `fk_Passenger_Flight1_idx` (`Flight_flightt's code` ASC) VISIBLE,
  CONSTRAINT `fk_Passenger_Flight1`
    FOREIGN KEY (`Flight_flightt's code`)
    REFERENCES `mydb`.`Flight` (`flightt's code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Online Reservation System`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Online Reservation System` (
  `id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Human`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Human` (
  `e-mail` VARCHAR(45) NOT NULL,
  `first name` VARCHAR(45) NOT NULL,
  `last name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone number` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`e-mail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Covid-19 Certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Covid-19 Certificate` (
  `AMKA` INT UNSIGNED NOT NULL,
  `number of doses` INT UNSIGNED NOT NULL,
  `date of last dose` DATE NOT NULL,
  PRIMARY KEY (`AMKA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `code` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `comments` TEXT(100) NULL,
  `Online Booking System_id` INT UNSIGNED NOT NULL,
  `Seat Type_type` VARCHAR(45) NOT NULL,
  `Human_e-mail` VARCHAR(45) NOT NULL,
  `search title` VARCHAR(45) NOT NULL,
  `flight type` VARCHAR(45) NOT NULL,
  `flight date` DATE NOT NULL,
  `description` TEXT(100) NULL,
  `Covid-19 Certificate_AMKA` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `fk_Reservation_Online Booking System1_idx` (`Online Booking System_id` ASC) VISIBLE,
  INDEX `fk_Reservation_Seat Type1_idx` (`Seat Type_type` ASC) VISIBLE,
  INDEX `fk_Reservation_Human1_idx` (`Human_e-mail` ASC) VISIBLE,
  INDEX `fk_Reservation_Covid-19 Certificate1_idx` (`Covid-19 Certificate_AMKA` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Online Booking System1`
    FOREIGN KEY (`Online Booking System_id`)
    REFERENCES `mydb`.`Online Reservation System` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Seat Type1`
    FOREIGN KEY (`Seat Type_type`)
    REFERENCES `mydb`.`Seat Type` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Human1`
    FOREIGN KEY (`Human_e-mail`)
    REFERENCES `mydb`.`Human` (`e-mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Covid-19 Certificate1`
    FOREIGN KEY (`Covid-19 Certificate_AMKA`)
    REFERENCES `mydb`.`Covid-19 Certificate` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `ticket's code` VARCHAR(45) NOT NULL,
  `QR code` INT UNSIGNED NOT NULL,
  `date of issue` DATE NOT NULL,
  `Passenger_passport id` VARCHAR(45) NOT NULL,
  `Reservation_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ticket's code`),
  INDEX `fk_Ticket_Passenger1_idx` (`Passenger_passport id` ASC) VISIBLE,
  INDEX `fk_Ticket_Reservation1_idx` (`Reservation_code` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Passenger1`
    FOREIGN KEY (`Passenger_passport id`)
    REFERENCES `mydb`.`Passenger` (`passport id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Reservation1`
    FOREIGN KEY (`Reservation_code`)
    REFERENCES `mydb`.`Reservation` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Union`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Union` (
  `name` VARCHAR(45) NOT NULL,
  `establishment year` YEAR(4) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Air Traffic Controller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Air Traffic Controller` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `latest medical examination date` DATE NOT NULL,
  `Airport_international airport code` CHAR(3) NOT NULL,
  `Union_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Air Traffic Controller_Airport1_idx` (`Airport_international airport code` ASC) VISIBLE,
  INDEX `fk_Air Traffic Controller_Union1_idx` (`Union_name` ASC) VISIBLE,
  CONSTRAINT `fk_Air Traffic Controller_Airport1`
    FOREIGN KEY (`Airport_international airport code`)
    REFERENCES `mydb`.`Airport` (`international airport code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Air Traffic Controller_Union1`
    FOREIGN KEY (`Union_name`)
    REFERENCES `mydb`.`Union` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technician` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone number` INT UNSIGNED NOT NULL,
  `salary` FLOAT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `Union_name` VARCHAR(45) NOT NULL,
  `Airport_international airport code` CHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Technician_Union1_idx` (`Union_name` ASC) VISIBLE,
  INDEX `fk_Technician_Airport1_idx` (`Airport_international airport code` ASC) VISIBLE,
  CONSTRAINT `fk_Technician_Union1`
    FOREIGN KEY (`Union_name`)
    REFERENCES `mydb`.`Union` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technician_Airport1`
    FOREIGN KEY (`Airport_international airport code`)
    REFERENCES `mydb`.`Airport` (`international airport code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technician_has_Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technician_has_Model` (
  `Technician_id` VARCHAR(45) NOT NULL,
  `Model_maker` VARCHAR(45) NOT NULL,
  `Model_seats` INT UNSIGNED NOT NULL,
  `Model_weight` DOUBLE NOT NULL,
  PRIMARY KEY (`Technician_id`, `Model_maker`, `Model_seats`, `Model_weight`),
  INDEX `fk_Technician_has_Model_Model1_idx` (`Model_maker` ASC, `Model_seats` ASC, `Model_weight` ASC) VISIBLE,
  INDEX `fk_Technician_has_Model_Technician1_idx` (`Technician_id` ASC) VISIBLE,
  CONSTRAINT `fk_Technician_has_Model_Technician1`
    FOREIGN KEY (`Technician_id`)
    REFERENCES `mydb`.`Technician` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technician_has_Model_Model1`
    FOREIGN KEY (`Model_maker` , `Model_seats` , `Model_weight`)
    REFERENCES `mydb`.`Model` (`maker` , `seats` , `weight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Check` (
  `name` VARCHAR(45) NOT NULL,
  `max score` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`name`, `max score`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Check_has_Civil Aviation Authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Check_has_Civil Aviation Authority` (
  `Check_name` VARCHAR(45) NOT NULL,
  `Check_max score` INT UNSIGNED NOT NULL,
  `Civil Aviation Authority_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Check_name`, `Check_max score`, `Civil Aviation Authority_id`),
  INDEX `fk_Check_has_Civil Aviation Authority_Civil Aviation Author_idx` (`Civil Aviation Authority_id` ASC) VISIBLE,
  INDEX `fk_Check_has_Civil Aviation Authority_Check1_idx` (`Check_name` ASC, `Check_max score` ASC) VISIBLE,
  CONSTRAINT `fk_Check_has_Civil Aviation Authority_Check1`
    FOREIGN KEY (`Check_name` , `Check_max score`)
    REFERENCES `mydb`.`Check` (`name` , `max score`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Check_has_Civil Aviation Authority_Civil Aviation Authority1`
    FOREIGN KEY (`Civil Aviation Authority_id`)
    REFERENCES `mydb`.`Civil Aviation Authority` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Control`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Control` (
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `score` FLOAT NOT NULL,
  `Technician_id` VARCHAR(45) NOT NULL,
  `Check_name` VARCHAR(45) NOT NULL,
  `Check_max score` INT UNSIGNED NOT NULL,
  `Aircraft_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`date`, `time`, `score`, `Technician_id`, `Check_name`, `Check_max score`, `Aircraft_id`),
  INDEX `fk_Control_Technician1_idx` (`Technician_id` ASC) VISIBLE,
  INDEX `fk_Control_Check1_idx` (`Check_name` ASC, `Check_max score` ASC) VISIBLE,
  INDEX `fk_Control_Aircraft1_idx` (`Aircraft_id` ASC) VISIBLE,
  CONSTRAINT `fk_Control_Technician1`
    FOREIGN KEY (`Technician_id`)
    REFERENCES `mydb`.`Technician` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Control_Check1`
    FOREIGN KEY (`Check_name` , `Check_max score`)
    REFERENCES `mydb`.`Check` (`name` , `max score`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Control_Aircraft1`
    FOREIGN KEY (`Aircraft_id`)
    REFERENCES `mydb`.`Aircraft` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
